### ISSUE TITLE
CShellExt::QueryContextMenu is leaking the bitmap used in the menu

### ISSUE THREAD

**Issue by chrdavis** [NTDLS/Secure-Archive#1]
This leaks the bitmap every time the context menu is invoked in explorer.  Make the bitmap a member of CShellExt and call DeleteObject on it in the destructor.

**Comment by NTDLS** [comment]
I'm just now seeing this. WTF?

**Comment by NTDLS** [comment]
Seriously, and people wonder why their computers need to be rebooted from time to time. Hey, maybe its that we get a new bitmap in ram every time you right-click. :/

**Comment by NTDLS** [comment]
@chrdavis Resolved in upcoming release, also added icon transparency.... probably 15 years too late. 😄
